# Generated by Django 2.2.6 on 2019-10-23 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.TextField()),
                ('ver_num', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('repo_size', models.PositiveSmallIntegerField()),
                ('prog_lang', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ('repo_name',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('state', models.PositiveSmallIntegerField()),
                ('complexity', models.PositiveSmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_references.Project')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_references.Task')),
            ],
            options={
                'db_table': 'docs',
            },
        ),
    ]
